/**
 * Application Constants
 * Centralized configuration values used throughout the application
 */

/**
 * Pagination Configuration
 */
export const PAGINATION = {
  DEFAULT_PAGE_SIZE: 8,
  ALLOWED_PAGE_SIZES: [8, 16, 24, 48, 96] as const,
  MAX_PAGE_SIZE: 10000, // For "show all" functionality
} as const;

/**
 * Payment Configuration (NZD - New Zealand Dollar)
 */
export const PAYMENT = {
  CURRENCY: 'NZD' as const,
  CENTS_PER_DOLLAR: 100,
  MINIMUM_CHARGE_AMOUNT: 0.50, // $0.50 minimum charge
  CURRENCY_LOCALE: 'en-NZ' as const, // for formatting amounts as NZD
} as const;

/**
 * Storage Keys
 */
export const STORAGE_KEYS = {
  CART: 'ecommerce_template_cart',
  ADMIN_AUTH: 'admin_auth_state',
} as const;

/**
 * Shipping Configuration
 * Customize these for your business location and shipping zones
 */
export const SHIPPING = {
  REGIONS: [
    "Region 1",
    "Region 2",
    "Region 3",
    "Region 4",
    "Region 5",
  ],
  COUNTRIES: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ],
} as const;

// Note: Removed CACHE.SHOP_PAGE_REVALIDATE - Next.js 16 requires segment config exports
// to be literal values, not imported constants. Use `export const revalidate = 60;` directly in page.tsx

/**
 * Environment Variables (type-safe access)
 * These will be validated at runtime
 */
export const ENV_KEYS = {
  DATABASE_URL: 'DATABASE_URL',
  BPC_GATEWAY_URL: 'BPC_GATEWAY_URL',
  BPC_API_KEY: 'BPC_API_KEY',
  BPC_WEBHOOK_SECRET: 'BPC_WEBHOOK_SECRET',
  ADMIN_PASSWORD: 'ADMIN_PASSWORD',
  RESEND_API_KEY: 'RESEND_API_KEY',
  BUSINESS_OWNER_EMAIL: 'BUSINESS_OWNER_EMAIL',
  EMAIL_FROM_ADDRESS: 'EMAIL_FROM_ADDRESS',
  EMAIL_FROM_NAME: 'EMAIL_FROM_NAME',
} as const;

